#!/usr/bin/env python3
"""tests/test_models_docs.py - docs/MODELS.md generation.

Covers that docs/MODELS.md is generated from the registry by sync and remains
current under sync --check.
"""

import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
_spec = importlib.util.spec_from_file_location("ae_models", REPO_ROOT / "scripts" / "models.py")
models = importlib.util.module_from_spec(_spec)
sys.modules["ae_models"] = models
_spec.loader.exec_module(models)

CLI = [sys.executable, str(REPO_ROOT / "scripts" / "models.py")]


def cli(*args, root=REPO_ROOT):
    return subprocess.run([*CLI, "--root", str(root), *args], capture_output=True, text=True)


class TestModelsDocGeneration:
    def test_models_md_is_generated_by_sync(self):
        """docs/MODELS.md is generated by sync."""
        result = cli("sync")
        assert result.returncode == 0
        models_md = REPO_ROOT / "docs" / "MODELS.md"
        assert models_md.is_file()

    def test_models_md_contains_role_table(self):
        """docs/MODELS.md includes role table with all roles."""
        models_md = (REPO_ROOT / "docs" / "MODELS.md").read_text()
        assert "## Roles" in models_md
        assert "| Role | Model | Effort | Fallback |" in models_md
        # Check all known roles appear
        roles = ["Engineer", "Orchestrator", "Senior Engineer", "Lead Engineer",
                 "Quality Engineer", "Principal Engineer", "Security Engineer", "Model Engineer"]
        for role in roles:
            assert f"**{role}**" in models_md, f"Missing role {role}"

    def test_models_md_contains_model_table(self):
        """docs/MODELS.md includes model table with all models."""
        models_md = (REPO_ROOT / "docs" / "MODELS.md").read_text()
        assert "## Models" in models_md
        assert "| Model ID | Family | Status | Verified | Claude | Copilot | OpenCode |" in models_md
        # Check all known models appear
        models_list = ["claude-haiku-4.5", "claude-sonnet-5", "claude-opus-5", "claude-fable-5"]
        for model in models_list:
            assert f"`{model}`" in models_md, f"Missing model {model}"

    def test_models_md_contains_pin_history(self):
        """docs/MODELS.md includes pin history summary."""
        models_md = (REPO_ROOT / "docs" / "MODELS.md").read_text()
        assert "## Pin History" in models_md
        assert "| Date | Role | From | To | Approval |" in models_md

    def test_models_md_has_generated_banner(self):
        """docs/MODELS.md has the GENERATED file banner."""
        models_md = (REPO_ROOT / "docs" / "MODELS.md").read_text()
        assert "<!-- GENERATED FILE" in models_md
        assert "scripts/models.py sync" in models_md

    def test_models_md_current_under_sync_check(self):
        """sync --check reports docs/MODELS.md as current."""
        result = cli("sync", "--check")
        assert result.returncode == 0
        assert "0 stale target(s)" in result.stdout

    def test_models_md_matches_registry_roles(self):
        """docs/MODELS.md role table matches registry exactly."""
        reg = models.load_registry()
        models_md = (REPO_ROOT / "docs" / "MODELS.md").read_text()

        for role, cfg in (reg.get("roles") or {}).items():
            model = cfg.get("model")
            effort = cfg.get("effort")
            assert f"| **{models.role_title(role)}** | `{model}` | {effort} |" in models_md

    def test_models_md_matches_registry_models(self):
        """docs/MODELS.md model table matches registry exactly."""
        reg = models.load_registry()
        models_md = (REPO_ROOT / "docs" / "MODELS.md").read_text()

        for mid, m in (reg.get("models") or {}).items():
            family = m.get("family")
            status = m.get("status")
            assert f"| `{mid}` | {family} | {status} |" in models_md

    def test_regenerate_models_md_is_idempotent(self):
        """Regenerating docs/MODELS.md produces identical output."""
        models_before = (REPO_ROOT / "docs" / "MODELS.md").read_text()
        cli("sync")
        models_after = (REPO_ROOT / "docs" / "MODELS.md").read_text()
        assert models_before == models_after
