#!/usr/bin/env python3
"""tests/test_locked_models_shim.py - LOCKED_MODELS.sh full-file generation.

Scope: LOCKED_MODELS.sh must be wholly generated by `python3 scripts/models.py sync`.
Hand-edits are overwritten (not preserved). The file is idempotent, sources correctly
in bash, exposes the documented API, and reflects registry changes (role re-pins).
"""

import importlib.util
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
LOCKED_SH = REPO_ROOT / ".githooks" / "LOCKED_MODELS.sh"

_spec = importlib.util.spec_from_file_location("ae_models", REPO_ROOT / "scripts" / "models.py")
models = importlib.util.module_from_spec(_spec)
sys.modules["ae_models"] = models
_spec.loader.exec_module(models)

CLI = [sys.executable, str(REPO_ROOT / "scripts" / "models.py")]
COPY_PATHS = ["config/models.yaml", "config/FRAMEWORK-MANIFEST.yaml", "src/AGENTS.md",
              "src/agents", ".githooks/LOCKED_MODELS.sh", ".agents_verification_sha", "docs/MODELS.md"]


def cli(*args, root=REPO_ROOT):
    return subprocess.run([*CLI, "--root", str(root), *args], capture_output=True, text=True)


def make_tree(tmp_path):
    for rel in COPY_PATHS:
        src, dst = REPO_ROOT / rel, tmp_path / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(src, dst) if src.is_dir() else shutil.copy2(src, dst)
    return tmp_path


class TestLockedModelsShFullGeneration:
    """AC1: Whole-file generation; hand-edits are overwritten."""

    def test_sync_fully_regenerates_file_overwrites_garbage(self, tmp_path):
        """Replacing file with garbage, then sync, restores it byte-for-byte."""
        root = make_tree(tmp_path)
        locked_sh = root / ".githooks" / "LOCKED_MODELS.sh"
        original = locked_sh.read_text(encoding="utf-8")

        # Corrupt: replace with garbage
        locked_sh.write_text("# GARBAGE HAND EDIT\necho 'broken'\n", encoding="utf-8")
        assert locked_sh.read_text() != original

        # Sync
        result = cli("sync", root=root)
        assert result.returncode == 0, f"sync failed: {result.stdout}\n{result.stderr}"

        # Should be restored exactly
        restored = locked_sh.read_text(encoding="utf-8")
        assert restored == original, "sync did not fully regenerate the file"

    def test_sync_idempotent_second_run_zero_diff(self, tmp_path):
        """Running sync twice: second run produces zero diff."""
        root = make_tree(tmp_path)
        locked_sh = root / ".githooks" / "LOCKED_MODELS.sh"

        # First sync
        r1 = cli("sync", root=root)
        assert r1.returncode == 0
        snap1 = locked_sh.read_text(encoding="utf-8")

        # Second sync
        r2 = cli("sync", root=root)
        assert r2.returncode == 0, f"second sync failed: {r2.stdout}\n{r2.stderr}"
        snap2 = locked_sh.read_text(encoding="utf-8")

        assert snap1 == snap2, "second sync changed the file (not idempotent)"

    def test_file_begins_with_generated_banner(self, tmp_path):
        """File starts with GENERATED banner, not hand-written prose."""
        root = make_tree(tmp_path)
        locked_sh = root / ".githooks" / "LOCKED_MODELS.sh"

        cli("sync", root=root)
        text = locked_sh.read_text(encoding="utf-8")

        # Must start with shebang and GENERATED
        assert text.startswith("#!/usr/bin/env bash"), "Missing shebang"
        assert "GENERATED" in text.split("\n")[3], "GENERATED banner missing from header"

        # Must NOT contain hand-written prose like 'single source of truth' literals
        assert "single source of truth" not in text.lower(), \
            "Hand-written 'single source of truth' prose should not appear"

    def test_bash_sourcing_exposes_arrays(self, tmp_path):
        """Sourcing the file in bash yields LOCKED_MODELS and AGENT_MODEL_ASSIGNMENTS arrays."""
        root = make_tree(tmp_path)
        locked_sh = root / ".githooks" / "LOCKED_MODELS.sh"

        cli("sync", root=root)

        result = subprocess.run(
            ["bash", "-c",
             f'source "{locked_sh}" && declare -p LOCKED_MODELS | grep -q "declare -ax" '
             f'&& declare -p AGENT_MODEL_ASSIGNMENTS | grep -q "declare -ax"'],
            capture_output=True, text=True,
        )
        assert result.returncode == 0, \
            f"arrays not exported or not arrays: stdout={result.stdout}, stderr={result.stderr}"

    def test_arrays_match_registry(self, tmp_path):
        """The bash arrays expose exactly what the registry specifies."""
        root = make_tree(tmp_path)
        locked_sh = root / ".githooks" / "LOCKED_MODELS.sh"

        cli("sync", root=root)
        reg = models.load_registry(root)

        # Extract array values from bash
        result = subprocess.run(
            ["bash", "-c",
             f'source "{locked_sh}" && '
             f'for m in "${{LOCKED_MODELS[@]}}"; do echo "model:$m"; done && '
             f'for a in "${{AGENT_MODEL_ASSIGNMENTS[@]}}"; do echo "assign:$a"; done'],
            capture_output=True, text=True,
        )
        assert result.returncode == 0, f"bash extraction failed: {result.stderr}"

        lines = result.stdout.strip().split("\n")
        bash_models = [l.split("model:", 1)[1] for l in lines if l.startswith("model:")]
        bash_assigns = [l.split("assign:", 1)[1] for l in lines if l.startswith("assign:")]

        # Check models
        expected_models = sorted(reg.get("models", {}).keys())
        assert sorted(bash_models) == expected_models, \
            f"LOCKED_MODELS array mismatch:\n  bash: {sorted(bash_models)}\n  expected: {expected_models}"

        # Check assignments
        expected_assigns = [
            f"{role}-agent:{cfg['model']}"
            for role, cfg in reg.get("roles", {}).items()
        ]
        assert sorted(bash_assigns) == sorted(expected_assigns), \
            f"AGENT_MODEL_ASSIGNMENTS mismatch:\n  bash: {sorted(bash_assigns)}\n  expected: {sorted(expected_assigns)}"

    def test_helper_functions_still_exist_and_work(self, tmp_path):
        """is_model_locked, get_agent_locked_model, show_* functions work."""
        root = make_tree(tmp_path)
        locked_sh = root / ".githooks" / "LOCKED_MODELS.sh"

        cli("sync", root=root)

        # Test is_model_locked
        result = subprocess.run(
            ["bash", "-c",
             f'source "{locked_sh}" && is_model_locked "claude-haiku-4.5" && echo "OK"'],
            capture_output=True, text=True,
        )
        assert result.returncode == 0 and "OK" in result.stdout, \
            f"is_model_locked failed: {result.stderr}"

        # Test get_agent_locked_model
        result = subprocess.run(
            ["bash", "-c",
             f'source "{locked_sh}" && get_agent_locked_model "engineer-agent" && echo "OK"'],
            capture_output=True, text=True,
        )
        assert result.returncode == 0 and "OK" in result.stdout, \
            f"get_agent_locked_model failed: {result.stderr}"

        # Test show_locked_models
        result = subprocess.run(
            ["bash", "-c",
             f'source "{locked_sh}" && show_locked_models | grep -q "claude-haiku" && echo "OK"'],
            capture_output=True, text=True,
        )
        assert result.returncode == 0 and "OK" in result.stdout, \
            f"show_locked_models failed: {result.stderr}"

    def test_fallback_notes_from_registry_not_hardcoded(self, tmp_path):
        """Fallback notes are rendered from registry, not hard-coded strings."""
        root = make_tree(tmp_path)
        locked_sh = root / ".githooks" / "LOCKED_MODELS.sh"
        reg_path = root / "config" / "models.yaml"

        # Edit registry: change a fallback
        reg = yaml.safe_load(reg_path.read_text())
        old_fb = reg["roles"]["engineer"]["fallback"]
        reg["roles"]["engineer"]["fallback"] = ["claude-sonnet-5.5"]  # Different fallback
        reg_path.write_text(yaml.safe_dump(reg, sort_keys=False))

        cli("sync", root=root)
        text = locked_sh.read_text(encoding="utf-8")

        # If fallback notes are rendered from registry, the file should reflect the change.
        # If they were hard-coded, they wouldn't change.
        # Sourcing and checking should work with new fallback.
        result = subprocess.run(
            ["bash", "-c", f'source "{locked_sh}" && echo "OK"'],
            capture_output=True, text=True,
        )
        assert result.returncode == 0, f"sourcing with new fallback failed: {result.stderr}"

    def test_bump_simulation_pin_change_reflected_in_file(self, tmp_path):
        """Re-pinning a role in registry is reflected in LOCKED_MODELS.sh after sync."""
        root = make_tree(tmp_path)
        locked_sh = root / ".githooks" / "LOCKED_MODELS.sh"
        reg_path = root / "config" / "models.yaml"

        # Get baseline
        cli("sync", root=root)
        before = locked_sh.read_text(encoding="utf-8")

        # Bump engineer from haiku to sonnet
        reg = yaml.safe_load(reg_path.read_text())
        old_model = reg["roles"]["engineer"]["model"]
        reg["roles"]["engineer"]["model"] = "claude-sonnet-5"
        # Add pin_history entry
        reg["pin_history"].append({
            "date": "2026-10-03",
            "role": "engineer",
            "from": old_model,
            "to": "claude-sonnet-5",
            "approval": "test: bump simulation"
        })
        reg_path.write_text(yaml.safe_dump(reg, sort_keys=False))

        # Sync and check
        cli("sync", root=root)
        after = locked_sh.read_text(encoding="utf-8")

        assert before != after, "sync did not reflect the role re-pin"
        assert "engineer-agent:claude-sonnet-5" in after, \
            "AGENT_MODEL_ASSIGNMENTS should contain new assignment"
