#!/usr/bin/env python3
"""tests/test_no_model_literals.py - lint test for bare model literals in prose.

Model IDs (claude-<family>-N[.N] and the hyphenated render claude-<family>-N-N) are
data owned by config/models.yaml. Prose that restates them drifts the moment a pin is
bumped, so the scanned prose files below must not contain them.

A literal is exempt only when it is:
- inside a fenced code block (``` ... ```), which is how format examples are written;
- inside the YAML frontmatter at the top of the file (generated by sync);
- on a line carrying the explicit marker `model-literal-ok` (an HTML comment such as
  `<!-- model-literal-ok: format example -->`), used sparingly and visibly;
- inside a generated block of src/AGENTS.md (the roster table rows and the per-role
  `**Model:**` lead lines, both rewritten from the registry by `models.py sync`);
- in docs/SPEC.md, inside the Update Log (historical changelog entries).

Everything else (including inline code spans, table rows and lines that merely say
"example" or "e.g.") is flagged. Replace the literal with role-based wording or a
link to docs/MODELS.md.

Where literals are allowed outright (not scanned): config/models.yaml, docs/MODELS.md,
.githooks/LOCKED_MODELS.sh, docs/decisions/, tests/.
"""

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent

# One pattern: canonical (claude-sonnet-5.5), rendered (claude-sonnet-5-5), bare major (claude-fable-5).
MODEL_PATTERNS = [r"claude-(?:haiku|sonnet|opus|fable)-\d+(?:[.-]\d+)?"]

MARKER = "model-literal-ok"

# Prose files that MUST exist and be clean. A missing file is a hard failure so that
# deleting or renaming a doc cannot silently drop it from the lint.
PROSE_FILES = [
    "README.md",
    "docs/ENTRYPOINT.md",
    "docs/CONTRIBUTING/README.md",
    "docs/guides/harness-setup/README.md",
    "docs/RENDERING.md",
    "docs/SPEC.md",
    ".githooks/LOCKED_MODELS_RATIONALE.md",
    "src/SKILLS.md",
    "src/AGENTS.md",
]

# Generated lines in src/AGENTS.md (rewritten from the registry by models.py sync).
_GENERATED_AGENTS_MD_LINES = (
    re.compile(r"^\| \*\*[^|]+\*\* \| claude-"),  # roster table rows
    re.compile(r"^\*\*Model:\*\* `claude-"),  # per-role lead line
)


def _find_model_literals(text: str, *, skip_update_log: bool = False,
                         generated_agents_md: bool = False) -> list[tuple[int, str]]:
    """Return (line_num, literal) for each non-exempt model literal in `text`."""
    findings: list[tuple[int, str]] = []
    lines = text.split("\n")
    in_fence = False
    in_frontmatter = bool(lines) and lines[0].strip() == "---"
    in_update_log = False
    for i, line in enumerate(lines, 1):
        stripped = line.strip()
        if in_frontmatter:
            if i > 1 and stripped == "---":
                in_frontmatter = False
            continue
        if stripped.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        if skip_update_log:
            if re.match(r"^## ", line):
                in_update_log = line.startswith("## Update Log")
            if in_update_log:
                continue
        if MARKER in line:
            continue
        if generated_agents_md and any(p.match(line) for p in _GENERATED_AGENTS_MD_LINES):
            continue
        for pattern in MODEL_PATTERNS:
            for match in re.finditer(pattern, line):
                findings.append((i, match.group(0)))
    return findings


def _scan_file(rel: str) -> list[tuple[int, str]]:
    path = REPO_ROOT / rel
    assert path.is_file(), f"{rel} is in the model-literal lint list but does not exist"
    return _find_model_literals(
        path.read_text(),
        skip_update_log=(rel == "docs/SPEC.md"),
        generated_agents_md=(rel == "src/AGENTS.md"),
    )


class TestNoBareLiterals:
    """Lint: no bare model literals in prose outside the narrow exemptions."""

    @pytest.mark.parametrize("prose_file", PROSE_FILES)
    def test_no_bare_literals_in_prose(self, prose_file):
        findings = _scan_file(prose_file)
        assert not findings, (
            f"Bare model literals in {prose_file}:\n"
            + "\n".join(f"  Line {n}: {lit}" for n, lit in findings)
            + "\n\nReplace with role-based wording or a link to docs/MODELS.md "
              "(config/models.yaml is the source of truth)"
        )

    def test_no_bare_literals_in_skill_prose(self):
        """SKILL.md bodies (frontmatter and fenced examples excluded) are clean."""
        skill_files = sorted((REPO_ROOT / "src/skills").rglob("SKILL.md"))
        assert skill_files, "no src/skills/*/SKILL.md found"
        problems = []
        for skill_file in skill_files:
            for n, lit in _find_model_literals(skill_file.read_text()):
                problems.append(f"{skill_file.relative_to(REPO_ROOT)}:{n}: {lit}")
        assert not problems, "Bare model literals in skill prose:\n  " + "\n  ".join(problems)

    def test_allowlist_is_complete(self):
        """Source-of-truth and generated files exist and carry the expected content."""
        assert (REPO_ROOT / "config/models.yaml").is_file()
        assert (REPO_ROOT / "docs/MODELS.md").is_file()
        assert (REPO_ROOT / ".githooks/LOCKED_MODELS.sh").is_file()
        models_md = (REPO_ROOT / "docs/MODELS.md").read_text()
        assert "<!-- GENERATED FILE" in models_md
        assert "claude-sonnet" in models_md


class TestLintMechanics:
    """The lint itself: it catches what it must and exempts only what it says."""

    def test_catches_planted_literal_in_a_temp_file(self, tmp_path):
        doc = tmp_path / "doc.md"
        doc.write_text("# T\n\nRuns on claude-sonnet-5.5 by default.\n")
        assert _find_model_literals(doc.read_text()) == [(3, "claude-sonnet-5.5")]
        doc.write_text("# T\n\nRendered as claude-opus-5-5 for Claude Code.\n")
        assert _find_model_literals(doc.read_text()) == [(3, "claude-opus-5-5")]

    def test_inline_code_table_and_example_wording_are_not_exempt(self):
        text = (
            "Use `claude-haiku-4.5` here.\n"
            "| role | claude-haiku-4.5 |\n"
            "For example claude-fable-5 works.\n"
            "e.g. claude-opus-4.8\n"
        )
        assert [n for n, _ in _find_model_literals(text)] == [1, 2, 3, 4]

    def test_exemptions_are_fence_frontmatter_marker_and_update_log(self):
        text = (
            "---\nmodel: claude-haiku-4.5\n---\n"
            "```yaml\nmodel: claude-sonnet-5.5\n```\n"
            "Marked claude-opus-5.5 <!-- model-literal-ok: format example -->\n"
            "## Body\nbare claude-fable-5\n"
            "## Update Log\n- entry mentions claude-sonnet-5\n"
        )
        assert _find_model_literals(text, skip_update_log=True) == [(9, "claude-fable-5")]
        # Without skip_update_log the log entry is flagged too.
        assert [n for n, _ in _find_model_literals(text)] == [9, 11]

    def test_missing_prose_file_is_a_hard_failure(self):
        with pytest.raises(AssertionError, match="does not exist"):
            _scan_file("docs/this-file-does-not-exist.md")
