#!/usr/bin/env python3
"""tests/test_no_model_literals.py - lint test for bare model literals in prose.

Bare model-version literals (claude-*-N.N, haiku/sonnet/opus/fable version mentions)
should only appear in:
- config/models.yaml (the registry, source of truth)
- docs/MODELS.md (generated reference)
- .githooks/LOCKED_MODELS.sh (generated hooks)
- src/agents/*-agent.md frontmatter (generated by sync)
- docs/decisions/ (ADRs and decision docs)
- tests/test_*.py (test fixtures, examples)
- Format examples explicitly marked as such in docstrings
- Inline code blocks marked as examples

This test forbids them elsewhere in docs, README, and skill prose.
"""

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent

# Model ID patterns to detect
MODEL_PATTERNS = [
    r"claude-(?:haiku|sonnet|opus|fable)-[\d.]+",  # canonical: claude-sonnet-5.5
    r"claude-(?:haiku|sonnet|opus|fable)-[\d]+-[\d]+",  # rendered: claude-sonnet-5-5
]

# Paths where model literals are ALLOWED (source of truth, generated, test fixtures)
ALLOWLIST_PATHS = {
    "config/models.yaml",
    "docs/MODELS.md",
    ".githooks/LOCKED_MODELS.sh",
    "tests/",  # test fixtures
    "docs/decisions/",  # ADRs
}

# Within these paths, inline examples are allowed if marked
EXAMPLES_ALLOWED = {
    "docs/",  # docs can have examples
    "src/skills/",  # skills can reference models in examples
}

# Files to check (prose only; code is checked separately)
PROSE_FILES = {
    "README.md",
    "docs/ENTRYPOINT.md",
    "docs/CONTRIBUTING/README.md",
    "src/SKILLS.md",
    "src/AGENTS.md",
}


def _should_check_file(path: Path) -> bool:
    """Return True if file should be checked for bare model literals."""
    rel = path.relative_to(REPO_ROOT)
    rel_str = str(rel)

    # Skip allowlisted paths
    for allowed in ALLOWLIST_PATHS:
        if rel_str.startswith(allowed):
            return False

    # Only check prose files, SKILL.md files, and specific docs
    if rel_str in PROSE_FILES:
        return True
    if rel_str.endswith("/SKILL.md"):
        return True
    if rel_str.startswith("docs/") and rel_str.endswith(".md"):
        if "decisions" not in rel_str and "MODELS.md" not in rel_str:
            return True

    return False


def _find_model_literals(text: str) -> list[tuple[int, str]]:
    """Return (line_num, matched_text) for each bare model literal found."""
    findings = []
    in_code_block = False
    for i, line in enumerate(text.split("\n"), 1):
        # Track code blocks; skip model literals inside them (they are examples)
        if "```" in line:
            in_code_block = not in_code_block
            continue

        if in_code_block:
            continue

        for pattern in MODEL_PATTERNS:
            for match in re.finditer(pattern, line):
                findings.append((i, match.group(0)))

    return findings


class TestNoBareLiterals:
    """Lint: no bare model literals in prose outside allowlist."""

    @pytest.mark.parametrize("prose_file", [
        "README.md",
        "docs/ENTRYPOINT.md",
        "docs/CONTRIBUTING/README.md",
        "src/SKILLS.md",
        "src/AGENTS.md",
    ])
    def test_no_bare_literals_in_prose(self, prose_file):
        """No bare model literals in {prose_file} outside explicit links to docs/MODELS.md."""
        path = REPO_ROOT / prose_file
        if not path.is_file():
            pytest.skip(f"{prose_file} not found")

        text = path.read_text()
        findings = _find_model_literals(text)

        # Filter: allow literals in links to docs/MODELS.md, backticks (inline code),
        # markdown table rows (auto-generated), or lines with "e.g." or "example"
        allowed_findings = []
        for line_num, lit in findings:
            line = text.split("\n")[line_num - 1]
            # Allow if: in link to MODELS.md, in backticks or code, in markdown table, or marked as example
            if (re.search(r"\[.*?docs/MODELS\.md.*?\]", line) or
                f"`{lit}" in line or  # backtick-wrapped code (partial match for hyphenated versions)
                "`" in line or  # line contains backticks (likely code)
                line.startswith("|") or  # markdown table row
                "e.g." in line or
                "example" in line.lower()):
                continue
            allowed_findings.append((line_num, lit))

        assert not allowed_findings, (
            f"Bare model literals in {prose_file}:\n" +
            "\n".join(f"  Line {line_num}: {lit}" for line_num, lit in allowed_findings) +
            f"\n\nReplace with role-based wording or link to docs/MODELS.md"
        )

    def test_no_bare_literals_in_skill_prose(self):
        """No bare model literals in skill SKILL.md files outside frontmatter and examples."""
        skill_files = list((REPO_ROOT / "src/skills").rglob("SKILL.md"))

        for skill_file in skill_files:
            text = skill_file.read_text()
            findings = _find_model_literals(text)

            # Filter: allow literals in frontmatter, code blocks, or explicit example sections
            allowed_findings = []
            in_frontmatter = True  # SKILL.md files start with frontmatter
            in_code_block = False
            for line_num, lit in findings:
                line = text.split("\n")[line_num - 1]

                # Skip frontmatter (auto-generated metadata) - ends at second ---
                if in_frontmatter:
                    if line.startswith("---") and line_num > 1:
                        in_frontmatter = False
                    continue

                if "```" in line:
                    in_code_block = not in_code_block
                    continue

                if in_code_block:
                    continue

                if "example" in line.lower() or "format" in line.lower() or "`" in line:
                    continue

                allowed_findings.append((line_num, lit))

            assert not allowed_findings, (
                f"Bare model literals in {skill_file.relative_to(REPO_ROOT)}:\n" +
                "\n".join(f"  Line {line_num}: {lit}" for line_num, lit in allowed_findings)
            )

    def test_allowlist_is_complete(self):
        """Verify allowlist paths exist and contain expected content."""
        # Verify source of truth files exist
        assert (REPO_ROOT / "config/models.yaml").is_file()
        assert (REPO_ROOT / "docs/MODELS.md").is_file()
        assert (REPO_ROOT / ".githooks/LOCKED_MODELS.sh").is_file()

        # Verify docs/MODELS.md was generated
        models_md = (REPO_ROOT / "docs/MODELS.md").read_text()
        assert "<!-- GENERATED FILE" in models_md
        assert "claude-sonnet" in models_md
