# -*- coding: utf-8 -*-
"""
housekeeping.py — Phase 4: .gitignore and README.md patching for repo-init.

Author: Senior Engineer
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import List, Tuple

_SKILL_ROOT = Path(__file__).parent.parent
_GITIGNORE_ADDITIONS = _SKILL_ROOT / "assets" / "gitignore-additions.txt"

_GITIGNORE_MARKER = "# agentic-engineers framework"

_README_SECTION = """
## Agentic Engineers

This repo uses the [agentic-engineers](https://github.com/{your-org}/agentic-engineers)
framework for AI-assisted development.

- See [docs/ONBOARDING.md](docs/ONBOARDING.md) to get started.
- See [docs/AGENTS.md](docs/AGENTS.md) for agent team configuration.
- See [TODO.md](TODO.md) for current task queue.
"""


def run_housekeeping(
    cfg, dry_run: bool = False
) -> Tuple[List[Path], List[Path]]:
    """
    Phase 4: Patch .gitignore and README.md.

    Returns:
        (files_created, files_modified)
    """
    created: List[Path] = []
    modified: List[Path] = []

    # .gitignore
    gitignore_path = cfg.repo_root / ".gitignore"
    if not gitignore_path.exists():
        if not dry_run:
            additions = _GITIGNORE_ADDITIONS.read_text(encoding="utf-8")
            gitignore_path.write_text(additions, encoding="utf-8")
            created.append(gitignore_path)
    else:
        existing = gitignore_path.read_text(encoding="utf-8")
        if _GITIGNORE_MARKER not in existing:
            if not dry_run:
                additions = _GITIGNORE_ADDITIONS.read_text(encoding="utf-8")
                gitignore_path.write_text(
                    existing.rstrip() + "\n\n" + additions, encoding="utf-8"
                )
                modified.append(gitignore_path)

    # README.md
    readme_path = cfg.repo_root / "README.md"
    if not readme_path.exists():
        if not dry_run:
            stub = _readme_stub(cfg)
            readme_path.write_text(stub, encoding="utf-8")
            created.append(readme_path)
    else:
        existing = readme_path.read_text(encoding="utf-8")
        if "Agentic Engineers" not in existing and "agentic-engineers" not in existing:
            if not dry_run:
                readme_path.write_text(
                    existing.rstrip() + "\n" + _README_SECTION, encoding="utf-8"
                )
                modified.append(readme_path)

    # Makefile (create minimal if missing)
    makefile_path = cfg.repo_root / "Makefile"
    if not makefile_path.exists():
        if not dry_run:
            makefile_path.write_text(_minimal_makefile(cfg), encoding="utf-8")
            created.append(makefile_path)
    else:
        existing = makefile_path.read_text(encoding="utf-8")
        if "agentic-engineers" not in existing and "validate-compat" not in existing:
            if not dry_run:
                makefile_path.write_text(
                    existing.rstrip() + "\n\n" + _makefile_addition(), encoding="utf-8"
                )
                modified.append(makefile_path)

    return created, modified


def _readme_stub(cfg) -> str:
    today = datetime.date.today().isoformat()
    return f"""# {cfg.project_name}

{cfg.project_description or 'A project built with the agentic-engineers framework.'}

## Getting Started

See [docs/ONBOARDING.md](docs/ONBOARDING.md) for setup instructions.

## Agentic Engineers

This repo uses the [agentic-engineers](https://github.com/{your-org}/agentic-engineers)
framework for AI-assisted development.

- See [docs/AGENTS.md](docs/AGENTS.md) for agent team configuration.
- See [TODO.md](TODO.md) for current task queue.

---
*README generated by repo-init v1.0 on {today}. Customize this file for your project.*
"""


def _minimal_makefile(cfg) -> str:
    return f"""# Makefile — {cfg.project_name}
# Generated by repo-init v1.0

.PHONY: help init-check validate-compat test

help:  ## Show available targets
\t@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \\
\t  awk 'BEGIN {{FS = ":.*?## "}}; {{printf "  %-20s %s\\n", $$1, $$2}}'

init-check:  ## Verify agentic-engineers framework is initialized
\t@test -f .agentic-engineers/INIT-COMPLETE.yaml && \\
\t  echo "✅ Framework initialized" || \\
\t  echo "❌ Not initialized — run: python3 src/skills/repo-init/scripts/repo_init.py --repo-root ."

validate-compat:  ## Run compatibility validation
\t@python3 src/skills/repo-init/scripts/validate_compatibility.py \\
\t  --repo-root . --report

test:  ## Run test suite
\t@python3 -m pytest tests/ -v
"""


def _makefile_addition() -> str:
    return """# agentic-engineers targets
.PHONY: init-check validate-compat

init-check:  ## Verify agentic-engineers framework is initialized
\t@test -f .agentic-engineers/INIT-COMPLETE.yaml && \\
\t  echo "✅ Framework initialized" || \\
\t  echo "❌ Not initialized — run repo-init"

validate-compat:  ## Run compatibility validation for agentic-engineers
\t@python3 src/skills/repo-init/scripts/validate_compatibility.py \\
\t  --repo-root . --report
"""
