#!/usr/bin/env python3
"""format_skill_report.py — Format validate_skills.py JSON as Markdown table.

Reads JSON from stdin (output of validate_skills.py --json) and writes a
Markdown table suitable for GitHub Actions step summaries.

Usage:
    python scripts/validate_skills.py --json | python scripts/format_skill_report.py
    python scripts/validate_skills.py --json | python scripts/format_skill_report.py >> "$GITHUB_STEP_SUMMARY"
"""
from __future__ import annotations

import json
import sys


def main() -> int:
    try:
        data = json.load(sys.stdin)
    except json.JSONDecodeError as e:
        print(f"_Error parsing skill report JSON: {e}_")
        return 1

    print("## Skill Template Conformance Report")
    print()
    print("| Skill | Status | Issues |")
    print("|-------|--------|--------|")

    for skill, info in sorted(data.items()):
        status = info.get("status", "UNKNOWN")
        icon = "✅" if status == "PASS" else ("⚠️" if status == "WARN" else "❌")
        issues = "; ".join(info.get("errors", []) + info.get("warnings", [])) or "—"
        # Truncate very long issue strings for table readability
        if len(issues) > 120:
            issues = issues[:117] + "..."
        print(f"| `{skill}` | {icon} {status} | {issues} |")

    print()
    passing = sum(1 for v in data.values() if v.get("status") == "PASS")
    total = len(data)
    print(f"_Conformance: {passing}/{total} skills passing. "
          f"Generated by Phase 5.1 `scripts/validate_skills.py`._")
    return 0


if __name__ == "__main__":
    sys.exit(main())
